name: Load TFLint Config
description: Loads a TFlint configuration file from a remote GitHub repository
author: terraform-linters
inputs:
  source-repo: 
    required: true
    description: The repository from which the configuration will be copied
  source-path:
    description: The directory in the remote repo where the configuration exists
    default: .
  source-filename:
    description: The source filename
    default: .tflint.hcl
  source-ref:
    description: Ref or branch of the remote repository to target
    default: ''
  destination-path:
    description: Directory to write the config file
    default: ${{ runner.temp }}
  destination-filename:
    description: Name of the configuration file to be written
    default: .tflint.hcl
  token:
    required: false
    description: Github access token, required for private repositories
outputs:
  path:
    description: The local path to the TFLint configuration file
runs:
  using: 'node12'
  main: 'dist/index.js'
