name: lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install yamlfmt
        run: |
          cd "$(mktemp -d)"
          curl --location --silent https://github.com/google/yamlfmt/releases/download/v0.5.0/yamlfmt_0.5.0_Linux_x86_64.tar.gz | tar zxvf -
          mv yamlfmt /usr/local/bin
      - run: yamlfmt -lint
