name: lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: go install github.com/google/yamlfmt/cmd/yamlfmt@v0.5.0
      - run: yamlfmt -lint
