name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: node-version
        uses: bendrucker/github-action-node-version@2b4cda19381b8015197f9a3eff1ec934716241da # v1.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: npm
      - run: npm ci
      - run: npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: load-config
        uses: ./
        with:
          source-repo: ${{ github.repository }}
          source-path: fixtures/.tflint.hcl
          source-ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: diff <(cat "${{ steps.load-config.outputs.path }}") fixtures/.tflint.hcl
